name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build library and tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run test
        run: ./test